spring.application.name=backend
spring.data.mongodb.uri=${MONGO_DB_LOCAL}
spring.security.oauth2.client.registration.github.client-id=${GITHUB_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_SECRET}
spring.security.oauth2.client.registration.github.scope=none
HOST_FRONTEND=http://localhost:5173/
HOST_BACKEND=http://localhost:8080/
JWT_SECRET:HbcQUymgp3uh/j9Fm4X3R2cvt0cTHb9t+9Q4TNAl+H9hl7UakAWj3sfXQMN+pykPRucfEoUps9GK656+YwihGA==
